if(NOT ${BUILD_TYPE} MATCHES Debug)
    include("${SOURCE_DIR}/Product.cmake")
    file(READ "${TARGET_SOURCE_DIR}/buildnumber.txt" BUILD_NUMBER)
	if(NOT ${BUILD_NUMBER})
		set(BUILD_NUMBER 1)
	endif()
    
	math(EXPR BUILD_NUMBER "${BUILD_NUMBER} + 1")
	if(${CMAKE_VERSION} VERSION_LESS 3.18)
		file(WRITE "${TARGET_SOURCE_DIR}/buildnumber.txt" "${BUILD_NUMBER}")
	else()
		file(CONFIGURE OUTPUT "${TARGET_SOURCE_DIR}/buildnumber.txt" CONTENT "${BUILD_NUMBER}")
	endif()
    file(REMOVE "${TARGET_SOURCE_DIR}/productmeta.h")
    configure_file("${TARGET_SOURCE_DIR}/productmeta.h.in" "${TARGET_SOURCE_DIR}/productmeta.h")
    file(TOUCH_NOCREATE "${TARGET_SOURCE_DIR}/${TARGET_NAME}.rc")
    
	message(STATUS "Build number set to ${BUILD_NUMBER} in ${TARGET_SOURCE_DIR}/buildnumber.txt")
endif()
